  const tourData = {
      national: [
    {
      slug: "leh-ladakh",
      name: "Leh Ladakh",
      district: "Leh",
      location: "Jammu & Kashmir",
      country: "India",
      price: 850,
      description: "Explore the majestic landscapes, Buddhist monasteries, and high-altitude passes of Leh and Ladakh.",
      details: "Leh Ladakh is a dream destination for adventure seekers and spiritual travelers alike. Famous for its dramatic mountain scenery, pristine lakes like Pangong and Tso Moriri, and rich Buddhist culture, it offers treks, motorbike expeditions, and tranquil retreats at monasteries such as Hemis and Thiksey.",
      images: [
        "/images/national/leh-ladakh/1.webp",
        "/images/national/leh-ladakh/2.webp",
        "/images/national/leh-ladakh/3.webp",
        "/images/national/leh-ladakh/4.webp",
        "/images/national/leh-ladakh/5.webp",
      ],
    },
    {
      slug: "gurudongmar-lake",
      name: "Gurudongmar Lake",
      district: "Mangan",
      location: "Sikkim",
      country: "India",
      price: 700,
      description: "Discover the serenity of one of the highest lakes in the world in the North Sikkim district of Mangan.",
      details: "Gurudongmar Lake, nestled at over 17,000 feet, is a mystical destination surrounded by snow-capped peaks. A sacred spot for both Buddhists and Sikhs, the lake remains frozen during winter and is a visual spectacle in summer, attracting pilgrims and nature lovers alike.",
      images: [
        "/images/national/gurudongmar-lake/1.webp",
        "/images/national/gurudongmar-lake/2.webp",
        "/images/national/gurudongmar-lake/3.webp",
        "/images/national/gurudongmar-lake/4.webp",
        "/images/national/gurudongmar-lake/5.webp",
      ],
    },
    {
      slug: "tawang",
      name: "Tawang",
      district: "Tawang",
      location: "Arunachal Pradesh",
      country: "India",
      price: 780,
      description: "Visit Tawang for its monasteries, mountain scenery, and Indo-Tibetan culture.",
      details: "Tawang is home to the famous Tawang Monastery, the largest in India, and is known for its spiritual ambiance and scenic beauty. With alpine forests, snow-capped peaks, and a rich blend of Tibetan culture, Tawang offers a peaceful yet captivating travel experience.",
      images: [
        "/images/national/tawang/1.webp",
        "/images/national/tawang/2.webp",
        "/images/national/tawang/3.webp",
        "/images/national/tawang/4.webp",
        "/images/national/tawang/5.webp",
      ],
    },
    {
      slug: "himachal",
      name: "Himachal",
      district: "Kullu-Manali",
      location: "Himachal Pradesh",
      country: "India",
      price: 750,
      description: "Explore snow-capped mountains, adventure sports, and picturesque valleys in Kullu-Manali.",
      details: "Himachal Pradesh, particularly Kullu-Manali, is a hub for outdoor enthusiasts. Activities like paragliding, river rafting, and skiing attract thrill-seekers, while its serene valleys, apple orchards, and temples make it perfect for relaxation and cultural exploration.",
      images: [
        "/images/national/himachal/1.webp",
        "/images/national/himachal/2.webp",
        "/images/national/himachal/3.webp",
        "/images/national/himachal/4.webp",
        "/images/national/himachal/5.webp",
      ],
    },
    {
      slug: "kerala",
      name: "Kerala",
      district: "Alappuzha",
      location: "South India",
      country: "India",
      price: 800,
      description: "Cruise through tranquil backwaters, unwind on beaches, and enjoy lush greenery in Alappuzha district.",
      details: "Kerala, often called 'God’s Own Country', enchants with its serene backwaters, traditional houseboats, Ayurvedic wellness resorts, and diverse wildlife. From the tranquil lagoons of Alappuzha to the spice plantations of Thekkady, it offers a complete and enriching travel experience.",
      images: [
        "/images/national/kerala/1.webp",
        "/images/national/kerala/2.webp",
        "/images/national/kerala/3.webp",
        "/images/national/kerala/4.webp",
        "/images/national/kerala/5.webp",
      ],
    },
    {
      slug: "rajasthan",
      name: "Rajasthan",
      district: "Jaisalmer",
      location: "West India",
      country: "India",
      price: 850,
      description: "Experience desert safaris, golden forts, and royal heritage in Jaisalmer.",
      details: "Jaisalmer, the 'Golden City', rises from the heart of the Thar Desert. Famous for its sandstone fort, havelis, and camel safaris, it offers a glimpse into royal Rajputana culture and a chance to explore the vast, mystical desert landscape under star-studded skies.",
      images: [
        "/images/national/rajasthan/1.webp",
        "/images/national/rajasthan/2.webp",
        "/images/national/rajasthan/3.webp",
        "/images/national/rajasthan/4.webp",
        "/images/national/rajasthan/5.webp",
      ],
    },
    {
      slug: "nepal-everest",
      name: "Nepal - Everest",
      district: "Solukhumbu",
      location: "Nepal",
      country: "Nepal",
      price: 1000,
      description: "Trek to the base camp of the world’s highest peak in the Solukhumbu district of Nepal.",
      details: "Nepal’s Everest region is a once-in-a-lifetime journey for trekkers, with routes offering awe-inspiring views of the Himalayas. From the bustling trailhead of Lukla to the serene base camp at the foot of Mount Everest, it's a spiritual and physical adventure unmatched anywhere else.",
      images: [
        "/images/national/everest/1.webp",
        "/images/national/everest/2.webp",
        "/images/national/everest/3.webp",
        "/images/national/everest/4.webp",
        "/images/national/everest/5.webp",
      ],
    },
    {
      slug: "puri",
      name: "Puri",
      district: "Puri",
      location: "Odisha",
      country: "India",
      price: 600,
      description: "Visit the sacred Jagannath Temple and relax on the Bay of Bengal beaches in Puri.",
      details: "Puri is a renowned pilgrimage site, best known for the grand Jagannath Temple and the vibrant Rath Yatra festival. It also offers beautiful beaches, traditional crafts, and cultural richness that make it an attractive destination for both spiritual seekers and beach lovers.",
      images: [
        "/images/national/puri/1.webp",
        "/images/national/puri/2.webp",
        "/images/national/puri/3.webp",
        "/images/national/puri/4.webp",
        "/images/national/puri/5.webp",
      ],
    },
    {
      slug: "sundarban",
      name: "Sundarban",
      district: "South 24 Parganas",
      location: "West Bengal",
      country: "India",
      price: 650,
      description: "Explore the tiger-inhabited mangrove forests and river deltas of South 24 Parganas.",
      details: "The Sundarbans is a UNESCO World Heritage Site, famed for its dense mangrove forests and elusive Royal Bengal Tigers. Tourists can enjoy boat safaris, observe unique biodiversity, and experience rural village life that’s deeply intertwined with the tides and the forests.",
      images: [
        "/images/national/sundarban/1.webp",
        "/images/national/sundarban/2.webp",
        "/images/national/sundarban/3.webp",
        "/images/national/sundarban/4.webp",
        "/images/national/sundarban/5.webp",
      ],
    },
    {
      slug: "dooars",
      name: "Dooars",
      district: "Jalpaiguri",
      location: "North Bengal",
      country: "India",
      price: 700,
      description: "Enjoy scenic landscapes, wildlife, and tea gardens in the foothills of the Himalayas in Jalpaiguri.",
      details: "The Dooars region is a hidden gem with lush forests, sprawling tea gardens, and rich wildlife. Ideal for nature lovers, it offers jeep safaris in Gorumara and Jaldapara, picturesque drives, and a peaceful escape into the lap of Himalayan foothills.",
      images: [
        "/images/national/dooars/1.webp",
        "/images/national/dooars/2.webp",
        "/images/national/dooars/3.webp",
        "/images/national/dooars/4.webp",
        "/images/national/dooars/5.webp",
      ],
    },
    {
      slug: "sikkim",
      name: "Sikkim",
      district: "Gangtok",
      location: "North East India",
      country: "India",
      price: 850,
      description: "Explore lakes, monasteries, and vibrant Himalayan culture in and around Gangtok.",
      details: "Sikkim is a land of pristine beauty and spiritual calm. From the alpine charm of Tsomgo Lake and Nathula Pass to colorful monasteries like Rumtek and Enchey, the state offers travelers a mix of natural wonder, adventure, and peaceful retreat into Himalayan culture.",
      images: [
        "/images/national/sikkim/1.webp",
        "/images/national/sikkim/2.webp",
        "/images/national/sikkim/3.webp",
        "/images/national/sikkim/4.webp",
        "/images/national/sikkim/5.webp",
      ],
    },
  ],



    international: [
    {
      slug: "bangkok-pattaya-krabi",
      name: "Bangkok, Pattaya & Krabi",
      district: "Bangkok / Chonburi / Krabi",
      location: "Southern Thailand",
      country: "Thailand",
      price: 1100,
      description: "A vibrant mix of bustling cities, exotic beaches, nightlife, and cultural temples in Thailand.",
      details: "This Thailand trio offers an unforgettable mix of urban excitement and coastal beauty. From Bangkok’s golden temples and floating markets to Pattaya’s nightlife and Krabi’s limestone cliffs and clear blue waters, this journey delivers vibrant culture, adventure, and stunning beach getaways in one unforgettable experience.",
      images: [
        "/images/international/thailand/1.webp",
        "/images/international/thailand/2.webp",
        "/images/international/thailand/3.webp",
        "/images/international/thailand/4.webp",
        "/images/international/thailand/5.webp",
      ],
    },
    {
      slug: "bali",
      name: "Bali",
      district: "Badung / Ubud",
      location: "Bali Island",
      country: "Indonesia",
      price: 1150,
      description: "An island paradise famous for beaches, waterfalls, temples, and serene rice terraces.",
      details: "Bali enchants with its lush green rice paddies, world-class surf spots, and deep spiritual charm. Visit Ubud’s art markets and monkey forest, soak in the sun on Seminyak’s beaches, and explore centuries-old temples set against volcanoes. It's a perfect destination for both relaxation and adventure.",
      images: [
        "/images/international/bali/1.webp",
        "/images/international/bali/2.webp",
        "/images/international/bali/3.webp",
        "/images/international/bali/4.webp",
        "/images/international/bali/5.webp",
      ],
    },
    {
      slug: "maldives",
      name: "Maldives",
      district: "Malé / South Atoll",
      location: "Indian Ocean",
      country: "Maldives",
      price: 1400,
      description: "Luxury overwater villas, coral reefs, and crystal-clear waters in a tropical island nation.",
      details: "The Maldives is a luxurious escape into turquoise waters and white sand beaches. Renowned for overwater bungalows, vibrant coral reefs, and world-class diving, it's perfect for honeymooners, couples, and ocean lovers seeking privacy, serenity, and some of the most stunning seascapes on Earth.",
      images: [
        "/images/international/maldives/1.webp",
        "/images/international/maldives/2.webp",
        "/images/international/maldives/3.webp",
        "/images/international/maldives/4.webp",
        "/images/international/maldives/5.webp",
      ],
    },
    {
      slug: "kenya",
      name: "Kenya",
      district: "Nairobi / Masai Mara / Amboseli",
      location: "East Africa",
      country: "Kenya",
      price: 1600,
      description: "Wildlife safari adventure across iconic national parks with views of Mount Kilimanjaro.",
      details: "Kenya promises a true African safari experience. Witness the Big Five in Masai Mara, gaze at Mount Kilimanjaro from Amboseli, and explore the cultural heartbeat of Nairobi. This journey blends wildlife, tribal heritage, and epic landscapes in one of Africa’s most iconic destinations.",
      images: [
        "/images/international/kenya/1.webp",
        "/images/international/kenya/2.webp",
        "/images/international/kenya/3.webp",
        "/images/international/kenya/4.webp",
        "/images/international/kenya/5.webp",
      ],
    },
    {
      slug: "thailand",
      name: "Thailand Highlights",
      district: "Chiang Mai / Phuket / Ayutthaya",
      location: "Central & Northern Thailand",
      country: "Thailand",
      price: 1050,
      description: "Temples, street food, island escapes, and rich culture across diverse Thai regions.",
      details: "This highlights tour captures Thailand's full spectrum — from ancient temples in Ayutthaya to the tranquil mountains of Chiang Mai and the tropical beaches of Phuket. With mouthwatering cuisine, friendly locals, and vibrant traditions, it’s a culturally rich and visually stunning journey.",
      images: [
        "/images/international/thailand/1.webp",
        "/images/international/thailand/2.webp",
        "/images/international/thailand/3.webp",
        "/images/international/thailand/4.webp",
        "/images/international/thailand/5.webp",
      ],
    },
    {
      slug: "bhutan",
      name: "Bhutan",
      district: "Paro / Thimphu",
      location: "Eastern Himalayas",
      country: "Bhutan",
      price: 900,
      description: "Peaceful monasteries, sacred sites, and mountain views in the Land of the Thunder Dragon.",
      details: "Bhutan is where nature and spirituality intertwine. Hike to the iconic Tiger’s Nest Monastery, stroll through serene dzongs, and witness a culture untouched by time. With its forested valleys, Himalayan views, and Gross National Happiness philosophy, Bhutan offers peace, beauty, and introspection.",
      images: [
        "/images/international/bhutan/1.webp",
        "/images/international/bhutan/2.webp",
        "/images/international/bhutan/3.webp",
        "/images/international/bhutan/4.webp",
        "/images/international/bhutan/5.webp",
      ],
    },
  ],



    jungle: [
    {
      slug: "tadoba",
      name: "Tadoba",
      district: "Chandrapur",
      location: "Maharashtra",
      country: "India",
      price: 700,
      description: "Wild tigers, bamboo forests, and rich biodiversity in Tadoba-Andhari Tiger Reserve.",
      details: "Tadoba is Maharashtra’s oldest and most thrilling tiger reserve, offering high chances of spotting wild tigers amidst bamboo thickets and teak forests. With scenic lakes and diverse fauna, it’s a top destination for wildlife photography and immersive jungle safaris.",
      images: [
        
        "/images/jungle/tadoba/2.webp",
        "/images/jungle/tadoba/3.webp",
        "/images/jungle/tadoba/4.webp",
        "/images/jungle/tadoba/1.webp",
        "/images/jungle/tadoba/5.webp",
      ],
    },
    {
      slug: "satpura",
      name: "Satpura",
      district: "Hoshangabad",
      location: "Madhya Pradesh",
      country: "India",
      price: 750,
      description: "Scenic and less crowded park with leopards, sloth bears, and boat safaris.",
      details: "Satpura offers a serene wilderness escape, with fewer tourists and more intimate wildlife encounters. Explore deep ravines, tranquil backwaters, and dense forests by boat, jeep, or even on foot. Spot leopards, sloth bears, and exotic birds in this hidden gem of Central India.",
      images: [
        "/images/jungle/satpura/1.webp",
        "/images/jungle/satpura/2.webp",
        "/images/jungle/satpura/3.webp",
        "/images/jungle/satpura/4.webp",
        "/images/jungle/satpura/5.webp",
      ],
    },
    {
      slug: "kanha",
      name: "Kanha",
      district: "Mandla",
      location: "Madhya Pradesh",
      country: "India",
      price: 800,
      description: "Lush sal forests, home to the rare Barasingha and majestic tigers.",
      details: "Kanha's vast meadows and dense sal forests inspired Kipling’s tales and remain a haven for wildlife. Watch tigers roam free, catch a glimpse of the rare Barasingha, and soak in one of India’s best-managed parks for a classic jungle adventure.",
      images: [
        "/images/jungle/kanha/1.webp",
        "/images/jungle/kanha/2.webp",
        "/images/jungle/kanha/3.webp",
        "/images/jungle/kanha/4.webp",
        "/images/jungle/kanha/5.webp",
      ],
    },
    {
      slug: "bandhavgarh",
      name: "Bandhavgarh",
      district: "Umaria",
      location: "Madhya Pradesh",
      country: "India",
      price: 850,
      description: "Compact park known for a high density of Royal Bengal tigers.",
      details: "Bandhavgarh is one of India’s top tiger spotting destinations, with the highest density of Royal Bengal tigers. Ancient ruins, forested hills, and open meadows create a cinematic backdrop for safaris packed with thrilling wildlife sightings and heritage intrigue.",
      images: [
        "/images/jungle/bandhavgarh/5.webp",
        "/images/jungle/bandhavgarh/2.webp",
        "/images/jungle/bandhavgarh/3.webp",
        "/images/jungle/bandhavgarh/4.webp",
        "/images/jungle/bandhavgarh/1.webp",
      ],
    },
    {
      slug: "pench",
      name: "Pench",
      district: "Seoni",
      location: "Madhya Pradesh",
      country: "India",
      price: 780,
      description: "Lush teak forests that inspired Kipling’s ‘The Jungle Book’.",
      details: "Pench's picturesque teak forests and winding rivers are straight out of Kipling’s imagination. This rich ecosystem is home to tigers, wild dogs, and leopards, offering both thrilling safaris and scenic beauty in a forest filled with literary and ecological charm.",
      images: [
        "/images/jungle/pench/1.webp",
        "/images/jungle/pench/2.webp",
        "/images/jungle/pench/3.webp",
        "/images/jungle/pench/4.webp",
        "/images/jungle/pench/5.webp",
      ],
    },
    {
      slug: "ranthambore",
      name: "Ranthambore",
      district: "Sawai Madhopur",
      location: "Rajasthan",
      country: "India",
      price: 900,
      description: "Majestic tigers amidst ruins of an ancient fort and dry deciduous forest.",
      details: "Ranthambore blends history and wildlife like nowhere else. Discover regal tigers prowling near ancient ruins and scenic lakes, set against a rugged Aravalli backdrop. Its dramatic fort, dry forests, and royal heritage make it one of India’s most iconic national parks.",
      images: [
        "/images/jungle/ranthambore/1.webp",
        "/images/jungle/ranthambore/2.webp",
        "/images/jungle/ranthambore/3.webp",
        "/images/jungle/ranthambore/4.webp",
        "/images/jungle/ranthambore/5.webp",
      ],
    },
    {
      slug: "dudhwa",
      name: "Dudhwa",
      district: "Lakhimpur Kheri",
      location: "Uttar Pradesh",
      country: "India",
      price: 820,
      description: "Remote and serene park with tigers, rhinos, and swamp deer.",
      details: "Dudhwa is a hidden sanctuary on the Terai belt, where grasslands meet forests in tiger and rhino territory. Less commercial and deeply biodiverse, it’s ideal for nature lovers seeking raw wilderness and rare sightings in a tranquil jungle setting.",
      images: [
        "/images/jungle/dudhwa/1.webp",
        "/images/jungle/dudhwa/2.webp",
        "/images/jungle/dudhwa/3.webp",
        "/images/jungle/dudhwa/4.webp",
        "/images/jungle/dudhwa/5.webp",
      ],
    },
    {
      slug: "kaziranga",
      name: "Kaziranga",
      district: "Golaghat / Nagaon",
      location: "Assam",
      country: "India",
      price: 950,
      description: "UNESCO World Heritage site, home to the Indian one-horned rhinoceros.",
      details: "Kaziranga’s floodplains host the largest population of one-horned rhinoceroses. A UNESCO site, it’s also rich in elephants, tigers, wild buffaloes, and birdlife. Vast grasslands and misty wetlands make it a photographer’s paradise and a must-visit for every wildlife enthusiast.",
      images: [
        "/images/jungle/kaziranga/1.webp",
        "/images/jungle/kaziranga/2.webp",
        "/images/jungle/kaziranga/3.webp",
        "/images/jungle/kaziranga/4.webp",
        "/images/jungle/kaziranga/5.webp",
      ],
    },
    {
      slug: "singalila",
      name: "Singalila",
      district: "Darjeeling",
      location: "West Bengal",
      country: "India",
      price: 870,
      description: "Cloud forests and rare red pandas at the Himalayan edge.",
      details: "Perched high in the Eastern Himalayas, Singalila offers misty trails, rhododendron forests, and rare red pandas. It's a dream for trekkers and birdwatchers, with panoramic views of Everest and Kanchenjunga on clear days — a unique blend of alpine wilderness and Himalayan magic.",
      images: [
        "/images/jungle/singalila/1.webp",
        "/images/jungle/singalila/2.webp",
        "/images/jungle/singalila/3.webp",
        "/images/jungle/singalila/4.webp",
        "/images/jungle/singalila/5.webp",
      ],
    },
    {
      slug: "jim-corbett",
      name: "Jim Corbett",
      district: "Nainital / Pauri Garhwal",
      location: "Uttarakhand",
      country: "India",
      price: 890,
      description: "India's oldest national park with rich wildlife and riverine forests.",
      details: "Jim Corbett is a legend among Indian national parks, offering rich biodiversity along the Ramganga River. From tiger tracking to birding and scenic forest lodges, its dramatic landscape of hills, rivers, and grasslands offers one of the best wildlife experiences in India.",
      images: [
        "/images/jungle/jim-corbett/1.webp",
        "/images/jungle/jim-corbett/2.webp",
        "/images/jungle/jim-corbett/3.webp",
        "/images/jungle/jim-corbett/4.webp",
        "/images/jungle/jim-corbett/5.webp",
      ],
    },
    {
      slug: "buxa",
      name: "Buxa",
      district: "Alipurduar",
      location: "West Bengal",
      country: "India",
      price: 720,
      description: "Lush forested area and tiger reserve near Bhutan border.",
      details: "Nestled at the Himalayan foothills near Bhutan, Buxa is a scenic reserve with dense forests, vibrant birdlife, and intriguing historic trails. Its lesser-known status makes it perfect for travelers seeking offbeat jungle charm with cultural and ecological richness.",
      images: [
        "/images/jungle/buxa/1.webp",
        "/images/jungle/buxa/2.webp",
        "/images/jungle/buxa/3.webp",
        "/images/jungle/buxa/4.webp",
        "/images/jungle/buxa/5.webp",
      ],
    },
    {
      slug: "sunderbans",
      name: "Sundarbans",
      district: "South 24 Parganas",
      location: "West Bengal",
      country: "India",
      price: 770,
      description: "UNESCO site and world’s largest mangrove forest, home to elusive Bengal tigers.",
      details: "The Sundarbans is a hauntingly beautiful world of tidal rivers and mangrove islands, sheltering saltwater-loving tigers. Explore this labyrinth by boat to experience its mystery, exotic birdlife, crocodiles, and the surreal interplay of land and water that defines this UNESCO biosphere.",
      images: [
        "/images/jungle/sunderbans/1.webp",
        "/images/jungle/sunderbans/2.webp",
        "/images/jungle/sunderbans/3.webp",
        "/images/jungle/sunderbans/4.webp",
        "/images/jungle/sunderbans/5.webp",
      ],
    },
  ]


  };

  export default tourData;
